spring.datasource.url=jdbc:postgresql://localhost:5432/dilrmp4-18-08-26
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.servlet.session.timeout=15m
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL =DEBUG
logging.level.org.hibernate.type= =TRACE
server.servlet.context-path=/
spring.resources.static-locations=classpath:/static/
spring.http.multipart.enabled=true
spring.http.multipart.max-file-size=10MB
spring.http.multipart.max-request-size=10MB
baseDirectory=C:/Utilization Certificate12
baseDirectorySanction=C:/Utilization Sanction
server.port=8086
erver.error.whitelabel.enabled=false
server.error.path=/error
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB