spring.datasource.url=jdbc:postgresql://10.247.203.123:5432/dilrmp4
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=Postgres@123
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/
spring.http.multipart.enabled=true
spring.http.multipart.max-file-size=10MB
spring.http.multipart.max-request-size=10MB
spring.resources.static-locations=classpath:/static/
baseDirectory=/opt/Utilization
baseDirectorySanction=/opt/Sanction
baseDirectoryTerm=/opt/term
server.servlet.session.timeout=15m
server.port=8086
logging.file.path=/home/spring
logging.file.name=dilrmp.log